AssetsDir 					= "assets"
Port 								= 8080
SessionSecret 			= "secret" # Change this to something random/unique, the longer the better

[DBConfig]
ConnectionString 	= "boat.db"
Dialect 					= "sqlite3"

[RendererConfig]
DisableCache 	= true
Extension 		= ".html"
Master 				= "layouts/master"
Root 					= "views"
Partials 			= [
	"partials/post",
	"partials/h-card"
]
