version: '3.1'
services:
  pg:
    image: postgres
    container_name: socialboat_pg
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data

