SiteName 			= "CrowderSoup"
TagLine       = "It's late and I don't know what to put here"
AssetsDir 		= "assets"
RootURL				= "http://localhost:8080"
Port 					= 8080
SessionSecret = "secret" # Change this to something random/unique, the longer the better

[DBConfig]
ConnectionString 	= "host=localhost port=5432 user=postgres dbname=socialboat password=password sslmode=disable"
Dialect 					= "postgres"

[RendererConfig]
DisableCache 	= true
Extension 		= ".html"
Master 				= "layouts/master"
Root 					= "views/themes/material" # Change to whatever theme you want
Partials 			= [
	"partials/post",
	"partials/h-card"
]
